"""Generate Chapter 2 records and the printed table from exact reference code."""
from pathlib import Path
import argparse
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "code/minidna"))
from minidna.duplex import chapter_example


def artifacts():
    record = chapter_example()
    rows = [("Top", "5' to 3'", record["top_5to3"]),
            ("Aligned partner", "3' to 5'", record["aligned_3to5"]),
            ("Partner, standard", "5' to 3'", record["partner_5to3"])]
    table_rows = [f"{name} & {direction} & " + r"\texttt{" + sequence + "}" + r" \\"
                  for name, direction, sequence in rows]
    table = (r"\begin{tabular}{lll}" + "\n" + r"\toprule View & Direction & Sequence \\" +
             "\n" + r"\midrule" + "\n" + "\n".join(table_rows) + "\n" +
             r"\bottomrule\end{tabular}" + "\n")
    return {"ch02.json": json.dumps(record, indent=2) + "\n",
            "ch02-table.tex": "% Generated by scripts/chapter02_artifacts.py; do not edit.\n" + table}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "book/results"
    for name, content in artifacts().items():
        path = target / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"stale generated artifact: {path}")
        else:
            target.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        print(path.relative_to(ROOT))
